### ISSUE TITLE
CI/CD of apache/fineract is broken

### ISSUE THREAD

**Issue by vorburger** [vorburger/www.fineract.dev#6]
The "CI/CD" from https://github.com/apache/fineract/ to demo.fineract.dev broke, a while ago.

https://demo.fineract.dev/fineract-provider/actuator/info shows the server is currently still at rev 97aa107 from 2021-07-08.

@ptuomola and @awasum have privately emailed me about this, but I've not yet had the time to look into it.

Today I'm creating this issue to public record finally investigating what's blocking this from working again.

**Comment by ptuomola** [comment]
Hello @vorburger - great to hear from you! 

Just FYI - I've removed the Github workflow that used to push to fineract.dev from the Fineract repository, as it was spamming everyone with emails about workflow failures. 

So when you have time to look into this, just restore it in Github so that you can investigate the failures...

**Comment by vorburger** [comment]
> Hello @vorburger - great to hear from you!

Same here!! How you keep at it is a motivation for me to sort this out... 😄 

> removed the Github workflow that used to push to fineract.dev from the Fineract repository, as it was spamming everyone with emails about workflow failures.

Totally fair! So FTR https://github.com/apache/fineract/commit/4522b71dfd11a885d7d5165f81e6d80db37e65ed can be reverted - once it works again.

https://github.com/apache/fineract/actions doesn't immediately show the failures anymore, but [status = failure filter](https://github.com/apache/fineract/actions?query=is%3Afailure) does...

> So when you have time to look into this, just restore it in Github so that you can investigate the failures...

https://github.com/apache/fineract/actions/runs/1219125759 has an:

> ERROR: (gcloud.beta.builds.triggers.run) INVALID_ARGUMENT: source.revision must be specified to run this trigger

I don't suppose by any chance you @ptuomola or @awasum happen to have already looked into this error message? (Looks like the `gcloud` CLI arguments changed.)

> just restore it in Github so that you can investigate the failures...

I can probably first to get it working manually locally again. Just need a quiet moment to remember exactly how I had set this up... 😃

**Comment by ptuomola** [comment]
> I don't suppose by any chance you @ptuomola or @awasum happen to have already looked into this error message? (Looks like the gcloud CLI arguments changed.)

I tried looking into it, but unfortunately https://cloud.google.com/sdk/gcloud/reference/beta/builds/triggers/run does not mention any such argument, so wasn't sure if this was something that was wrong in the trigger definition (which I can't see) or in the command line. I played around with the arguments for a while but didn't really make any progress...

**Comment by vorburger** [comment]
> I can probably first to get it working manually locally again. 

So if I locally run `gcloud beta builds triggers run deploy-demo` (from [here](https://github.com/apache/fineract/commit/4522b71dfd11a885d7d5165f81e6d80db37e65ed#diff-2a9c0143ea98680c567e8762bdaa3d47578544eb9f80042593370a81b766b08aL38)) then it actually reproduces that `source.revision` error.

PS: It needs my personal credentials, of course; I can't really see how I could make this publicly available (and let any push), unfortunately.

**Comment by vorburger** [comment]
> locally run `gcloud beta builds triggers run deploy-demo` then it actually reproduces that `source.revision` error.
> https://cloud.google.com/sdk/gcloud/reference/beta/builds/triggers/run does not mention any such argument

There's a `--branch` argument - and that seems to be it, I (locally) seem get further when I add that! Something is currently running (slow!)... I got to stop for today; I'll pick this up some future evening.

BTW https://cloud.google.com/sdk/gcloud/reference/beta/builds/triggers/run also ends with "This command is currently in BETA and may change without notice." - I guess we noticed, LOL. 😈 

> moment to remember exactly how I had set this up... 
> wasn't sure if this was something that was wrong in the trigger definition (which I can't see)

Right, so `deploy-demo` is indeed a trigger definition in a Git repo that I current still keep private which has a bunch of scripts that make https://www.fineract.dev "tick". I've never shared them publicly mostly out of a concern for not being willing to "support" them (other than for running fineract.dev).

**Comment by vorburger** [comment]
Fixed! https://demo.fineract.dev/fineract-provider/actuator/info is now at 5532f84 from 2021-09-11 - that was manual.

https://github.com/apache/fineract/pull/1870 re-enables the GitHub action that automates future updates again (as it was).

Done.
