### ISSUE TITLE
Opening up Fineract.dev Error Reporting to trusted committers

### ISSUE THREAD

**Issue by vorburger** [vorburger/www.fineract.dev#9]
Seeing @ptuomola fix https://github.com/apache/fineract/pull/1980/files for https://issues.apache.org/jira/browse/FINERACT-1089 reminded me of the general https://issues.apache.org/jira/browse/FINERACT-932, and I had an idea / suggestion / proposal:

@ptuomola, or anyone else reading along here, would you have any interest in being able to have view access to (only) the Error Reporting for Fineract.dev on the Google Cloud Console? Would you have any interest in occassionally checking it out? I believe it may be possible for me to set this up with a few clicks.

BTW if interested, what is your view about just making this completely publicly accessible, or just to some (Google, not Fineract) logins? My initial thought here is that security wise it's perhaps not a great idea to expose logs to anyone, unauthenticated. Even if Fineract.dev is just a demo instance, I'm not entirely comfortable to completely open up the console. (If it's even possible on Google Cloud; I have not looked at the details of how to do this, yet.)

**Comment by vorburger** [comment]
@ptuomola I have gone ahead and tried out a first related configuration ("IAM"); if I did it correctly, you should now be able to view https://console.cloud.google.com/errors?&project=vorburger-learn-appengin (if you login with your personal Google account on which we have emailed in the past). Check it out and let me know if that works or if I missed something (and if you want to keep it or prefer having this removed again, for any reason).

> completely open up the console. (If it's even possible on Google Cloud; I have not looked at the details of how to do this, yet.)

It seems like it's not - at least there is no "open to the 'world' principal" (or no obvious one; I didn't search a lot).

**Comment by ptuomola** [comment]
Hi - that works well for me, I can access and see the errors - which is great!

**Comment by vorburger** [comment]
Cool. I've now also granted you "Cloud Build Viewer", so in addition to that Error Reporting you should be able to also see e.g. https://console.cloud.google.com/cloud-build/builds;region=global/e54a0a48-fbc0-44d6-b961-8d651b1ea972?project=vorburger-learn-appengin & Co. It occured to me that this may be handy and useful for you in the future as well.

Let me resolve this. I don't mind adding additional trusted committers to grant visiblity into Fineract.dev Error Reporting as needed - just ask, see https://github.com/vorburger/www.fineract.dev/commit/7de40df2e34ecea3aa388b77e062e9c2a16ee9a8.

**Comment by jdailey** [comment]
Michael - maybe you could add me and anyone else on the Security list.  That way, if there's a reported issue we can *potentially* reproduce it on dev and see in the log the result.  It may be useful in some limited scenarios.

**Comment by vorburger** [comment]
> maybe you could add me

done

**Comment by vorburger** [comment]
> Cool. I've now also granted you "Cloud Build Viewer", so in addition to that Error Reporting you should be able to also see e.g. https://console.cloud.google.com/cloud-build/builds;region=global/e54a0a48-fbc0-44d6-b961-8d651b1ea972?project=vorburger-learn-appengin & Co. It occured to me that this may be handy and useful for you in the future as well.

FTR: This apparently did not quite work yet - I've just created new #10 to sort this out.

**Comment by vorburger** [comment]
@vidakovic @awasum if getting the same access would interest you as well, then please privately email me your Google (Gmail) Account ID.

**Comment by vorburger** [comment]
FTR @vidakovic also has access now.

**Comment by vorburger** [comment]
FTR @awasum also has access now.

**Comment by vorburger** [comment]
FTR @BLasan also has access now, based on interest in https://issues.apache.org/jira/browse/FINERACT-1266.
